; Settings for Simplified Animations
; Lines beginning with a semicolon are comments, which are ignored.
; Change ONLY the words "true" or "false" in the text below, and ONLY to exactly "true" or exactly "false".

[CombatEffects]
; Disables the bright flashing Big Slash visual effect, used by Perfected Strike,
; Sovereign Blade and the Mecha Knight
DisableBigSlashEffect=true

; Disables the purple screen effect when an enemy dies because of Doom
DisablePurpleDoomOverlay=true

; Disable the radial blur/distortion effect used by some enemy attacks
; (Bygone Effigy, Ceremonial Beast, Mecha Knight, Shrinker Beetle, Vantom)
DisableRadialBlurEffect=true

; Disable the "scream" effect (concentric circles moving outwards) used by some enemy attacks
; (Ceremonial Beast, Devoted Sculptor, Terror Eel, The Insatiable)
DisableScreamEffect=true

; Disable the similar "spooky scream" effect used by some other enemy attacks
; (Haunted Ship, Soul Fysh)
DisableSpookyScreamEffect=true

[Environments]
; Disables the "sandfalls" in the background of The Insatiable
DisableInsatiableSandfalls=true

; Disables the other sand effects (but the sandfalls are left unless disabled above)
DisableOtherInsatiableSandEffects=true

; Hides the rain effect in the Slippery Bridge event
DisableRainEffect=true

[Gameplay]
; Reduces (essentially removes) the delay between drawing one card and
; drawing the next, making all cards move together to the hand
QuickerDraw=true

[Timeline]
; Disable the radiating shockwave animation on the Epoch buttons (and replaces the offscreen animation
; with an arrow, showing that there are more unlocks available by scrolling left, right or both)
DisableUnlockShockwaves=true

; Disable the movement of starry background
FreezeBackgroundStars=true

; Hides the constant confetti from the unlock screens (for example relics or cards)
HideConfetti=true

[UI]
; Disables the glow effect around rare/uncommon cards
DisableRareCardGlow=true
DisableUncommonCardGlow=true
