; Settings for Simplified Animations
; Lines beginning with a semicolon are comments, which are ignored.
; Change ONLY the words "true" or "false" in the text below, and ONLY to exactly "true" or exactly "false".

[Cards]
; Disables the bright flashing Big Slash visual effect, used by Perfected Strike,
; Sovereign Blade and the Mecha Knight
DisableBigSlashEffect=true

[Events]
; Hides the rain effect in the Slippery Bridge event
DisableRainEffect=true

[Timeline]
; Hides the constant confetti from the unlock screens (for example relics or cards)
HideConfetti=true

; Disable the movement of starry background
FreezeBackgroundStars=true

; Disable the radiating shockwave animation on the Epoch buttons (and replaces the offscreen animation
; with an arrow, showing that there are more unlocks available by scrolling left, right or both)
DisableUnlockShockwaves=true