; Settings for Simplified Animations
; Lines beginning with a semicolon are comments, which are ignored.
; Change ONLY the words "true" or "false" in the text below, and ONLY to exactly "true" or exactly "false".

[Events]
; Hides the rain effect in the Slippery Bridge event
DisableRainEffect=true

[Gameplay]
; Reduces (essentially removes) the delay between drawing one card and
; drawing the next, making all cards move together to the hand
QuickerDraw=true

[VFX]
; Disables the bright flashing Big Slash visual effect, used by Perfected Strike,
; Sovereign Blade and the Mecha Knight
DisableBigSlashEffect=true

; Disables the purple screen effect when an enemy dies because of Doom
DisablePurpleDoomOverlay=true

[Timeline]
; Disable the movement of starry background
FreezeBackgroundStars=true

; Hides the constant confetti from the unlock screens (for example relics or cards)
HideConfetti=true

; Disable the radiating shockwave animation on the Epoch buttons (and replaces the offscreen animation
; with an arrow, showing that there are more unlocks available by scrolling left, right or both)
DisableUnlockShockwaves=true